<?php

namespace App\Http\Controllers;

use App\Models\Home;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = 'Travel';
        $numberAdults = [1, 2, 3, 4, 5, 6, 7, 8, 9];
        $numberChildres = [1, 2, 3, 4, 5, 6, 7, 8, 9];

        $aeroports = [
            'OUROLANDIA DO NORTE',
            'HOTEL TRANSAMÉRICA',
            'SORRISO',
            'MONTREAL-MIRABEL INTERNATIONAL AIRPORT',
            'QUEBEC CITY JEAN LESAGE INTERNATIONAL AIRPORT',
            'WINNIPEG JAMES ARMSTRONG RICHARDSON INTERNATIONAL AIRPORT',
            'CALGARY INTERNATIONAL AIRPORT',
            'TORONTO PEARSON INTERNATIONAL AIRPORT',
            'HOUARI BOUMEDIENNE AIRPORT',
            'BATNA AIRPORT',
            'OUAGADOUGOU AIRPORT',
            'KOTOKA INTERNATIONAL AIRPORT',
            'PORT BOUET AIRPORT (FELIX HOUPHOUET BOIGNY INTERNATIONAL AIRPORT)',
            'NNAMDI AZIKIWE INTERNATIONAL AIRPORT',
            'MURTALA MOHAMMED INTERNATIONAL AIRPORT',
            'PORT HARCOURT INTERNATIONAL AIRPORT',
            'TUNIS - CARTHAGE INTERNATIONAL AIRPORT',
            'LOME-TOKOIN AIRPORT',
            'BRUSSELS AIRPORT',
            'BRUSSELS SOUTH CHARLEROI AIRPORT',
            'LIEGE AIRPORT',
            'OSTEND-BRUGES INTERNATIONAL AIRPORT',
            'BERLIN-SCHÃ–NEFELD INTERNATIONAL AIRPORT',
            'FRANKFURT INTERNATIONAL AIRPORT',
            'HAMBURG AIRPORT',
            'COLOGNE BONN AIRPORT',
            'DUSSELDORF INTERNATIONAL AIRPORT',
            'MUNICH INTERNATIONAL AIRPORT (FRANZ JOSEF STRAUÃŸ INTERNATIONAL AIRPORT)',
            'SAARBRUCKEN AIRPORT',
            'STUTTGART ECHTERDINGEN AIRPORT',
            'TEGEL INTERNATIONAL AIRPORT',
            'HANOVER/LANGENHAGEN INTERNATIONAL AIRPORT',
            'FRANKFURT-HAHN AIRPORT',
            'HAMBURG FINKENWERDER AIRPORT',
            'BIRMINGHAM AIRPORT',
            'COTSWOLD AIRPORT',
            'MOD SAINT ATHAN',
            'LONDON LUTON AIRPORT',
            'LASHAM AIRFIELD',
            'LONDON GATWICK AIRPORT',
            'LONDON HEATHROW AIRPORT',
            'KENT INTERNATIONAL AIRPORT',
            'BARROW/WALNEY ISLAND AIRFIELD',
            'NEWCASTLE AIRPORT',
            'EAST MIDLANDS AIRPORT',
            'GLASGOW INTERNATIONAL AIRPORT',
            'GLASGOW PRESTWICK INTERNATIONAL AIRPORT',
            'NORWICH INTERNATIONAL AIRPORT',
            'LONDON STANSTED AIRPORT',
            'EXETER INTERNATIONAL AIRPORT',
            'AMSTERDAM AIRPORT SCHIPHOL',
            'MAASTRICHT AACHEN AIRPORT',
            'WOENSDRECHT AIR BASE',
            'SHANNON AIRPORT',
            'COPENHAGEN AIRPORT',
            'LUXEMBOURG FINDEL AIRPORT',
            'OSLO AIRPORT',
            'WARSAW FREDERIC CHOPIN AIRPORT (OKECIE INTERNATIONAL AIRPORT)',
            'GÃ–TEBORG-LANDVETTER AIRPORT',
            'STOCKHOLM-ARLANDA AIRPORT',
            'RÄªGAINTERNATIONALAIRPORT',
            'CAPE TOWN INTERNATIONAL AIRPORT',
            'OR TAMBO INTERNATIONAL AIRPORT',
            'LANSERIA AIRPORT',
            'KING SHAKA INTERNATIONAL AIRPORT',
            'OR TAMBO INTERNATIONAL AIRPORT',
            'UPINGTON AIRPORT',
            'WONDERBOOM AIRPORT',
            'MAYA-MAYA AIRPORT',
            'POINTE NOIRE AIRPORT',
            'MALABO AIRPORT',
            'YAOUNE NSIMALEN INTERNATIONAL AIRPORT',
            'LUSAKA INTERNATIONAL AIRPORT',
            'QUATRO DE FEVEREIRO AIRPORT',
            'MAPUTO INTERNATIONAL AIRPORT',
            'HARARE INTERNATIONAL AIRPORT',
            'WINDHOEK HOSEA KUTAKO INTERNATIONAL AIRPORT',
            'BANJUL INTERNATIONAL AIRPORT (YUNDUM INTÂ´L)',
            'LA PALMA AIRPORT',
            'GRAN CANARIA AIRPORT',
            'LANZAROTE AIRPORT',
            'TENERIFE SOUTH AIRPORT',
            'TENERIFE NORTH AIRPORT',
            'CAPE PALMAS AIRPORT',
            'MONROVIA',
            'AGADIR/ AL MASSLRA',
            'MOULAY ALI CHERIF AIRPORT',
            'AEROPORTO INTERNACIONAL MOHAMMED V',
            'MARRAKECH/MENARA',
            'DACAR',
            'NOUAKCHOTT INTERNATIONAL AIRPORT',
            'CONAKRY/GBESSIA',
            'AEROPORTO INTERNACIONAL AMÃLCAR CABRAL',
            'FRANCISCO MENDES',
            'CABO VERDE',
            'BOLE INTERNATIONAL AIRPORT',
            'CAIRO INTERNATIONAL AIRPORT',
            'JOMO KENYATTA INTERNATIONAL AIRPORT (FORMERLY NAIROBI INTERNATIONAL AIRPORT)',
            'ANDREWS AIR FORCE BASE',
            'HARTSFIELD JACKSON ATLANTA INTERNATIONAL AIRPORT',
            'AUSTIN BERGSTROM INTERNATIONAL AIRPORT',
            'BOEING FIELD/KING COUNTY INTERNATIONAL AIRPORT',
            'BANGOR INTERNATIONAL AIRPORT',
            'BIRMINGHAM-SHUTTLESWORTH INTERNATIONAL AIRPORT',
            'HERNANDO COUNTY AIRPORT',
            'NASHVILLE INTERNATIONAL AIRPORT',
            'LOGAN INTERNATIONAL AIRPORT',
            'BALTIMORE-WASHINGTON INTERNATIONAL THURGOOD MARSHALL AIRPORT',
            'CHARLESTON INTERNATIONAL AIRPORT (CHARLESTON AIR FORCE BASE)',
            'CLEVELAND HOPKINS INTERNATIONAL AIRPORT',
            'CHARLOTTE/DOUGLAS INTERNATIONAL AIRPORT',
            'DALLAS LOVE FIELD',
            'DENVER INTERNATIONAL AIRPORT (STAPLETON INTÂ´L)',
            'DALLAS-FORT WORTH INTERNATIONAL AIRPORT',
            'DOTHAN REGIONAL AIRPORT',
            'DOVER AIR FORCE BASE',
            'DETROIT METROPOLITAN WAYNE COUNTY AIRPORT',
            'EL PASO INTERNATIONAL AIRPORT',
            'NEWARK LIBERTY INTERNATIONAL AIRPORT',
            'FAIRFIELD MUNICIPAL AIRPORT',
            'FORT LAUDERDALE-HOLLYWOOD INTERNATIONAL AIRPORT',
            'PIEDMONT TRIAD INTERNATIONAL AIRPORT',
            'GREAT FALLS INTERNATIONAL AIRPORT',
            'GREENWOOD-LEFLORE AIRPORT',
            'GOODYEAR MUNICIPAL AIRPORT',
            'WILLIAM P. HOBBY AIRPORT',
            'HUNTSVILLE INTERNATIONAL AIRPORT (CARL T. JONES FIELD)',
            'MCCONNELL AIR FORCE BASE',
            'WASHINGTON DULLES INTERNATIONAL AIRPORT',
            'GEORGE BUSH INTERCONTINENTAL AIRPORT',
            'AIRBORNE AIRPARK',
            'INDIANAPOLIS INTERNATIONAL AIRPORT',
            'JACKSONVILLE INTERNATIONAL AIRPORT',
            'JOHN F. KENNEDY INTERNATIONAL AIRPORT',
            'MCCARRAN INTERNATIONAL AIRPORT',
            'LOS ANGELES INTERNATIONAL AIRPORT',
            'LAKE CHARLES REGIONAL AIRPORT',
            'LAKE CITY GATEWAY AIRPORT',
            'CLINTON NATIONAL AIRPORT/ADAMS FIELD',
            'KANSAS CITY INTERNATIONAL AIRPORT',
            'ORLANDO INTERNATIONAL AIRPORT',
            'MEMPHIS INTERNATIONAL AIRPORT',
            'MIAMI INTERNATIONAL AIRPORT',
            'LOUIS ARMSTRONG INTERNATIONAL AIRPORT',
            'PINAL AIRPARK',
            'WILL ROGERS WORLD AIRPORT',
            'ONTARIO INTERNATIONAL AIRPORT',
            'OPA-LOCKA AIRPORT',
            'OÂ´HARE INTERNATIONAL AIRPORT',
            'ORLANDO EXECUTIVE AIRPORT',
            'SNOHOMISH COUNTY AIRPORT (PAINE FIELD)',
            'PALM BEACH INTERNATIONAL AIRPORT',
            'PORTLAND INTERNATIONAL AIRPORT',
            'PHILADELPHIA INTERNATIONAL AIRPORT',
            'PHOENIX SKY HARBOR INTERNATIONAL AIRPORT',
            'CHICAGO ROCKFORD INTERNATIONAL AIRPORT',
            'MARCH AIR RESERVE BASE',
            'GRIFFISS AIRPORT',
            'ROSWELL INTERNATIONAL AIR CENTER AIRPORT',
            'SOUTHWEST FLORIDA INTERNATIONAL AIRPORT',
            'SAN DIEGO INTERNATIONAL AIRPORT (LINDBERGH FIELD)',
            'SAN ANTONIO INTERNATIONAL AIRPORT',
            'SAN BERNARDINO INTERNATIONAL AIRPORT',
            'SEATTLE-TACOMA INTERNATIONAL AIRPORT',
            'ORLANDO SANFORD INTERNATIONAL AIRPORT',
            'SAN FRANCISCO INTERNATIONAL AIRPORT',
            'NORMAN Y. MINETA SAN JOSÃ‰ INTERNATIONAL AIRPORT',
            'LAMBERT SAINT LOUIS INTERNATIONAL AIRPORT',
            'TRAVIS AIR FORCE BASE',
            'TAMPA INTERNATIONAL AIRPORT',
            'TULSA INTERNATIONAL AIRPORT',
            'TUCSON INTERNATIONAL AIRPORT',
            'SOUTHERN CALIFORNIA LOGISTICS AIRPORT',
            'MCGUIRE AIR FORCE BASE',
            'SOFIA INTERNATIONAL AIRPORT (VRAZHDEBNA)',
            'BARCELONA-EL PRAT AIRPORT',
            'ADOLFO SUÃREZ MADRID-BARAJAS AIRPORT',
            'MÃLAGA-COSTA DEL SOL AIRPORT',
            'PALMA DE MALLORCA AIRPORT',
            'MATACÃN AIRPORT',
            'SANTIAGO DE COMPOSTELA AIRPORT',
            'MADRID-TORREJÃ“N AIRPORT',
            'VALENCIA AIRPORT',
            'VITORIA AIRPORT',
            'ZARAGOZA AIRPORT',
            'SAN PABLO AIRPORT',
            'BORDEAUX MÃ‰RIGNAC AIRPORT',
            'FRANCAZAL',
            'TOULOUSE - BLAGNAC AIRPORT',
            'TARBES - LOURDES PYRENEES AIRPORT',
            'FIGEAC',
            'MARSEILLE PROVENCE AIRPORT',
            'MONTPELLIER-MÃ‰DITERRANÃ‰E AIRPORT',
            'FLERS SAINT-PAUL AIRPORT',
            'CHÃ‚LONS VATRY AIRPORT',
            'PARIS LE BOURGET AIRPORT',
            'BEYNES THIVERVAL AIRPORT',
            'PARIS-CHARLES DE GAULLE AIRPORT (ROISSY AIRPORT)',
            'PARIS ORLY AIRPORT',
            'NANTES ATLANTIQUE AIRPORT (FORMERLY AÃ‰ROPORT CHÃ‚TEAU BOUGON)',
            'EUROAIRPORT BASEL-MULHOUSE-FREIBURG',
            'NÃŽMES-ALÃˆS-CAMARGUE-CÃ‰VENNES AIRPORT (GARONS AIRPORT)',
            'ELLINIKON INTERNACIONAL AIRPORT',
            'LISZT FERENC INTERNATIONAL AIRPORT',
            'CASALE AIRPORT',
            'PALERMO AIRPORT (PUNTA RAISI AIRPORT)',
            'MALPENSA INTERNATIONAL AIRPORT',
            'TURIN INTERNATIONAL AIRPORT (TORINO CASELLE AIRPORT)',
            'GENOA CRISTOFORO COLOMBO AIRPORT (SESTRI AIRPORT)',
            'LINATE AIRPORT',
            'BRESCIA AIRPORT GABRIELE D ANNUNZIO',
            'CIAMPINO AIRPORT (GIOVAN BATTISTA PASTINE AIRPORT)',
            'LEONARDO DA VINCI INTERNATIONAL AIRPORT (FIUMICINO INTERNATIONAL AIRPORT)',
            'NAPLES INTERNATIONAL AIRPORT (CAPODICHINO AIRPORT)',
            'OSTRAVA-MOÅ NOV INTERNATIONAL AIRPORT',
            'GAZA AIRSTRIP (FORMERLY GUSH KATIF AIRPORT)',
            'BEN GURION INTERNATIONAL AIRPORT',
            'MALTA INTERNATIONAL AIRPORT (LUQA AIRPORT)',
            'ALVERCA AB',
            'SANTA MARIA AIRPORT',
            'FARO / MADEIRA AND ACORES',
            'AEROPORTO DE MADEIRA',
            'LAJES AIR BASE INT.',
            'PORTO',
            'PORTO SANTO AIRPORT',
            'LISBOA',
            'GENEVA COINTRIN INTERNATIONAL AIRPORT',
            'ZÃœRICH AIRPORT (KLOTEN AIRPORT)',
            'ANTALYA AIRPORT',
            'ATATÃœRK INTERNATIONAL AIRPORT',
            'SABIHA GÃ–KÃ‡EN INTERNATIONAL AIRPORT',
            'MILAN RASTISLAV Å TEFÃNIK AIRPORT (BRATISLAVA AIRPORT)',
            'LA ROMANA INTERNATIONAL AIRPORT',
            'PUNTA CANA',
            'SAO DOMINGO/DE LAS AMERICAS',
            'AEROPORTO INTERNACIONAL LA AURORA',
            'KINGSTON/NORMAN MANLEY INTL',
            'GENERAL JUAN N. ÃLVAREZ INTERNATIONAL AIRPORT',
            'GUADALAJARA/INTL',
            'GENERAL SERVANDO CANALES INTERNATIONAL AIRPORT',
            'MERIDA',
            'BENITO JUAREZ INTL',
            'MONTERREY',
            'PUEBLA',
            'LIC. GUSTAVO DÃAZ ORDAZ INTERNATIONAL AIRPORT',
            'ING. FERNANDO ESPINOZA GUTIÃ‰RREZ INTERNATIONAL AIRPORT',
            'LOS CABOS INTERNATIONAL AIRPORT',
            'TIJUANA',
            'TOLUCA',
            'TAPACHULA INTERNATIONAL AIRPORT',
            'CANCUN/INTL',
            'GENERAL HERIBERTO JARA INTERNATIONAL AIRPORT',
            'MANAGUA',
            'HOWARD AFB',
            'PANAMA PACIFICO, FORMERLY HOWARD AIR FORCE BASE',
            'TOCUMEN INTL',
            'DANIEL ODUBER INTERNATIONAL AIRPORT',
            'SAN JOSE/JUAN SANTAMARIA',
            'AIRPORT SAN JOSE CIUDAD',
            'SAN SALVADOR',
            'AEROPORTO INTERNACIONAL TOUSSAINT LOUVERTURE',
            'MAXIMO GOMEZ AIRPORT',
            'JARDINES DEL REY AIRPORT',
            'VILO ACUNA AIRPORT (JUAN VITALIO ACUNA AIRPORT)',
            'IGNÃCIO AGRAMONTE INTERNATIONL AIRPORT',
            'ANTONIO MACEO AIRPORT',
            'HAVANA',
            'FRANK PAÃS AIRPORT',
            'CIUDAD LIBERTAD AIRPORT',
            'SANTA CLARA',
            'JUAN GUALBERTO GOMEZ AIRPORT',
            'GRAND BAHAMA INTERNATIONAL AIRPORT',
            'AEROPORTO INTERNACIONAL LYNDEN PINDLING',
            'CHRISTCHURCH',
            'MAZAR AIRPORT',
            'KING ABDULAZIZ INTERNATIONAL AIRPORT',
            'PRINCE MOHAMMAD BIN ABDULAZIZ AIRPORT',
            'RIAD/KING KHALED INTL',
            'AB DHABI INTERNATIONAL',
            'DUBAI',
            'DUBAI INTERNATIONAL AIRPORT',
            'SHARJAH INTERNATIONAL AIRPORT',
            'MUSCAT INTERNATIONAL AIRPORT',
            'DAMASCUS',
            'DOHA INTERNATIONAL AIRPORT',
            'HAMAD INTERNATIONAL AIRPORT',
            'TED STEVENS ANCHORAGE INTERNATIONAL AIRPORT',
            'NARITA INTERNATIONAL AIRPORT',
            'NEW CHITOSE AIRPORT',
            'INCHEON INTERNATIONAL AIRPORT',
            'GIMPO INTERNATIONAL AIRPORT',
            'ROSARIO - ISLAS MALVINAS INTERNATIONAL AIRPORT',
            'JORGE NEWBERY AIRPORT',
            'INGENIERO AMBROSIO L.V. TARAVELLA INTERNATIONAL AIRPORT',
            'MINISTRO PISTARINI INTERNATIONAL AIRPORT (EZEIZA INTERNATIONAL AIRPORT)',
            'IGUAZU',
            'GOVERNOR FRANCISCO GABRIELLI INTERNATIONAL AIRPORT (EL PLUMERILLO INTÂ´L)',
            'SAN MARTÃN AIRPORT',
            'COMODORO D. RICARDO SALOMÃ“N AIRPORT',
            'MENDOZA, MZA',
            'TTE. GRAL. BENJAMÃN MATIENZO INTERNATIONAL AIRPORT',
            'DOCTOR FERNANDO PIRAGINE NIVEYRO INTERNATIONAL AIRPORT',
            'RESISTENCIA INTERNATIONAL AIRPORT',
            'CATARATAS DEL IGUAZÃš INTERNATIONAL AIRPORT (IGUAZÃš FALLS)',
            'MARTÃN MIGUEL DE GÃœEMES INTERNATIONAL AIRPORT (EL AYBAL AIRPORT)',
            'ORÃN AIRPORT',
            'ALMIRANTE MARCO ANDRÃ‰S ZAR AIRPORT',
            'BRIGADIER HECTOR EDUARDO RUIZ AIRPORT',
            'PIGUE',
            'ASTOR PIAZZOLLA INTERNATIONAL AIRPORT',
            'PRESIDENTE PERÃ“N INTERNATIONAL AIRPORT',
            'SAN CARLOS DE BARILOCHE AIRPORT',
            'CONCEIÇÃO DO ARAGUAIA',
            'BAURU/AREALVA',
            'CAMPO DOS AFONSOS',
            'ANGRA DOS REIS  ',
            'AMAPÁ',
            'BASE AEREA DE ANAPOLIS',
            'BARTOLOMEU DE GUSMÃO',
            'SANTA MARIA',
            'MARCELO PIRES HALZHAUSEN',
            'DEPUTADO BENEDITO SANTIAGO',
            'ESTADUAL DARIO GUARITA',
            'USINA PORTO PRIMAVERA ',
            'ROMEU ZEMA',
            'VAL DE CANS',
            'COMANDANTE GUSTAVO KRAEMER',
            'PAMPULHA - CARLOS DRUMMOND DE ANDRADE',
            'BACACHERI',
            'MAJOR BRIGADEIRO DO AR DOORGAL GOMES',
            'PRESIDENTE JUSCELINO KUBITSCHEK',
            'CHAFEI AMSEI',
            'BAURU',
            'ATLAS BRASIL CANTANHEDE',
            'BARRA DO GARÇAS',
            'UMBERTO MODIANO ',
            'ADALBERTO MENDES DA SILVA',
            'CABO FRIO',
            'CACHIMBO',
            'CARLOS ALBERTO DA COSTA NEVES',
            'TANCREDO NEVES',
            'CAMPO GRANDE',
            'SERAFIN ENOSS BERTASO',
            'BRIGADEIRO LYSIAS AUGUSTO RODRIGUES',
            'CARAJÁS',
            'DIOMÍCIO FREITAS',
            'NELSON RODRIGUES GUIMARÃES',
            'CANOAS',
            'BARTOLOMEU LISANDRO',
            'CORUMBÁ',
            'AFONSO PENA',
            'CARAVELAS',
            'REGIONAL HUGO CANTERGIANI',
            'MARECHAL RONDON',
            'CRUZEIRO DO SUL',
            'BONITO',
            'PRESIDENTE PRUDENTE',
            'AEROPORTO MUNCIPAL DE DOURADOS',
            'EDUARDO GOMES',
            'JACAREACANGA',
            'TENENTE LUND PRESETTO',
            'CATARATAS',
            'HERCÍLIO LUZ',
            'FERNANDO DE NORONHA',
            'PINTO MARTINS',
            'AEROPORTO INTERNACIONAL DO RIO DE JANEIRO/GALEÃO – ANTONIO CARLOS JOBIM',
            'GUAJARÁ-MIRIM',
            'SANTA GENOVEVA',
            'EMBRAER-UNIDADE GAVIAO PEIXOTO',
            'GUARULHOS - GOVERNADOR ANDRÉ FRANCO MONTORO',
            'PONTA GROSSA',
            'TANCREDO THOMAS DE FARIA',
            'CORONEL ALTINO MACHADO',
            'ALTAMIRA',
            'ITACOATIARA',
            'ITAITUBA',
            'BAHIA - JORGE AMADO',
            'USIMINAS',
            'Aeroporto de Itumbiara - Francisco Vilela do Amaral',
            'PREFEITO RENATO MOREIRA',
            'REGIONAL SUL',
            'JÚLIO CESAR',
            'AEROPORTO DE JUNDIAÍ',
            'FRANCISCO DE ASSIS',
            'JI-PARANÁ',
            'PRESIDENTE CASTRO PINTO',
            'JACAREPAGUÁ/RJ - ROBERTO MARINHO',
            'ORLANDO BEZERRA DE MENEZES',
            'LAURO CARNEIRO DE LOYOLA',
            'PRESIDENTE JOÃO SUASSUNA',
            'VIRACOPOS',
            'HORÁCIO DE MATTOS',
            'CORREIA PINTO',
            'GOVERNADOR LUCAS NOGUEIRA GARCEZ',
            'GOVERNADOR JOSÉ RICHA',
            'BOM JESUS DA LAPA',
            'MARABÁ',
            'MINAÇU',
            'MONTE DOURADO',
            'MACAÉ',
            'REGIONAL DE MARINGÁ - SÍLVIO NAME JÚNIOR',
            'MARINGÁ',
            'MÁRIO RIBEIRO',
            'FRANK MILOYE MILENKOVICH',
            'PONTA PELADA ',
            'ZUMBI DOS PALMARES',
            'MACAPÁ',
            'DIX-SEPT ROSADO',
            'CAMPO DE MARTE',
            'MANICORÉ',
            'MINISTRO VICTOR KONDER',
            'SANTO ÂNGELO',
            'AUGUSTO SEVERO',
            'OIAPOQUE',
            'SALGADO FILHO',
            'PREFEITO DOUTOR JOÃO SILVA FILHO',
            'EMBAIXADOR WALTHER MOREIRA SALLES',
            'LAURO KURTZ',
            'BRIGADEIRO LYSIAS RODRIGUES',
            'PELOTAS',
            'SENADOR NILO COELHO',
            'PALMAS ',
            'PORTO NACIONAL',
            'PONTA PORÃ',
            'PORTO SEGURO',
            'GOVERNADOR JORGE TEIXEIRA DE OLIVEIRA',
            'VITÓRIA DA CONQUISTA',
            'PLÁCIDO DE CASTRO',
            'RONDONÓPOLIS',
            'GUARARAPES - GILBERTO FREYRE',
            'RIO GRANDE',
            'SANTOS DUMONT',
            'LEITE LOPES',
            'BARTOLOMEU DE GUSMAO  ',
            'SÃO GONÇALO DO AMARANTE',
            'PROFESSOR URBANO ERNESTO STUMPF',
            'MARECHAL CUNHA MACHADO',
            'SANTA MARIA',
            'MAESTRO WILSON FONSECA',
            'CONGONHAS',
            'PROFESSOR ERIBERTO MANOEL REINO',
            'BASE AEREA',
            'DEPUTADO LUÍS EDUARDO MAGALHÃES',
            'TROMBETAS',
            'HOTEL TRANSAMÉRICA',
            'LUÍS DAL CANALLE FILHO',
            'SENADOR PETRÔNIO PORTELLA',
            'TEFÉ',
            'AEROPORTO REGIONAL PLÍNIO ALARCON',
            'TARAUACÁ',
            'TELÊMACO BORBA',
            'TORRES',
            'TIRIOS',
            'TABATINGA',
            'TUCURUÍ',
            'TERRAVISTA',
            'SÃO GABRIEL DA CACHOEIRA',
            'PAULO AFONSO',
            'RUBEM BERTA',
            'TENENTE-CORONEL AVIADOR CÉSAR BOMBONATO',
            'MÁRIO DE ALMEIDA FRANCO',
            'URUCU',
            'MAJOR BRIGADEIRO TROMPOWSKY',
            'BRIGADEIRO CAMARÃO',
            'EURICO DE AGUIAR SALLES',
            'IAUARETÊ',
            'CAMPO FONTENELLE/ACADEMIA DA FORÇA AÉREA',
            'REGIONAL DA ZONA DA MATA',
            'CHACALLUTA INTERNATIONAL AIRPORT',
            'EL LOA AIRPORT',
            'CARLOS IBANEZ DEL CAMPO INTERNATIONAL AIRPORT',
            'DIEGO ARACENA INTERNATIONAL AIRPORT',
            'COMODORO ARTURO MERINO BENÃTEZ INTERNATIONAL AIRPORT',
            'CERRO MORENO INTERNATIONAL AIRPORT',
            'CARRIEL SUR INTERNATIONAL AIRPORT',
            'LA ARAUCANIA AIRPORT',
            'EL TEPUAL INTERNATIONAL AIRPORT',
            'LOS CERRILLOS AIRPORT',
            'ARARAS',
            'ANGRA DOS REIS',
            'AMARAIS',
            'BEBEDOURO',
            'TANCREDO DE ALMEIDA NEVES',
            'SENADORA EUNICE MICHILES',
            'SOROCABA',
            'CABO FRIO',
            'CACULÉ',
            'FAZENDA SANTA LUZIA',
            'MARICÁ',
            'OURINHOS',
            'MOZARLÂNDIA',
            'OURILÂNDIA DO NORTE',
            'FAZ. PORTO BELO',
            'RESENDE',
            'MÁRIO PEREIRA LOPES',
            'PARATI',
            'GASTÃO MADEIRA',
            'ITAPERUNA',
            'VERA CRUZ',
            'DOMINGOS PIGNATARI',
            'AEROPORTO REGIONAL DE ZONA DA MATA',
            'JOSE  JOAQUIN DE OLMEDO INTERNATIONAL AIRPORT',
            'COTOPAXI INTERNATIONAL AIRPORT',
            'ELOY ALFARO INTERNATIONAL AIRPORT',
            'MARISCAL SUCRE INTERNATIONAL AIRPORT',
            'QUITO',
            'SILVIO PETTIROSSI INTERNATIONAL AIRPORT',
            'GUARANI INTERNATIONAL AIRPORT',
            'CATOLÉ DO ROCHA',
            'ARACRUZ',
            'GAVIAO PEIXOTO',
            'COLIDER',
            'LUCAS DO RIO VERDE',
            'LARANJAL DO JARI',
            'TENENTE LUND PRESETTO',
            'BOTELHO',
            'BARRA GRANDE',
            'FAZENDA SANTO AMBROSIO',
            'AEROCLUBE DE ELDORADO DO SUL',
            'JUARA SUL',
            'JATAPU',
            'BONITO',
            'AERÓDROMO ARAGUATINS',
            'CONFRESA  ',
            'COTRIGUACU',
            'LEÃO DE OURO',
            'MISSAO CATRIMANI',
            'NOVO PROGRESSO',
            'BARRA DO VENTO  ',
            'ESTÂNCIA REBOG',
            'RIO GRANDE',
            'MOUSSA NAKHL TOBIAS',
            'TERRA SANTA',
            'FAZENDA VISTA ALEGRE',
            'TERRAVISTA',
            'ARAGARÇAS',
            'EL DORADO INTERNATIONAL AIRPORT',
            'ERNESTO CORTISSOZ INTERNATIONAL AIRPORT',
            'RAFAEL NUNEZ INTERNATIONAL AIRPORT',
            'ALFONSO BONILLA ARAGÃ“N INTERNATIONAL AIRPORT',
            'ALFREDO VÃSQUEZ COBO INTERNATIONAL AIRPORT',
            'OLAYA HERRERA AIRPORT',
            'MATECAÃ‘A INTERNATIONAL AIRPORT',
            'JOSÃ‰ MARÃA CÃ“RDOVA INTERNATIONAL AIRPORT',
            'JORGE WILSTERMANN INTERNATIONAL AIRPORT',
            'CONCEPCIÃ“N AIRPORT',
            'EL ALTO INTERNATIONAL AIRPORT',
            'PUERTO SUÃREZ INTERNATIONAL AIRPORT',
            'SANTA ANA DEL YACUMA AIRPORT',
            'TENIENTE JORGE HENRICH ARAUZ AIRPORT',
            'VIRU VIRU INTERNATIONAL AIRPORT',
            'JOHAN ADOLF PENGEL INTERNATIONAL AIRPORT (ZANDERIJ INTÂ´L)',
            'PARAMARIBO',
            'ARARIPINA',
            'ADUSTINA',
            'JANAÚBA',
            'ARACATI',
            'AGROVALE',
            'CHAFEI AMSEI',
            'BACABAL',
            'BARREIRAS',
            'BALSAS',
            'BRUMADO',
            'CAMPO DE BOI ',
            'BAIÃO',
            'BARRA',
            'CAMPO DE BOI',
            'CIBRASA',
            'RURÓPOLIS',
            'REDENÇÃO',
            'ABA',
            'CHAPADA DIAMANTINA',
            'DOMINGOS REGO',
            'DIAMANTINA',
            'BRIGADEIRO CABRAL',
            'PARAGOMINAS',
            'COMANDANTE PASCHOAL PATROCÍNIO FILHO',
            'SÃO FÉLIX DO XINGU',
            'GUANAMBI',
            'GOVERNADOR VALADARES',
            'SANTA MAGALHÃES',
            'IRECÊ',
            'IGUATU',
            'IPIAÚ',
            'JACOBINA',
            'JOÃO DURVAL CARNEIRO',
            'JEQUIÉ',
            'SÃO JOÃO DEL REI',
            'SANTANA DO ARAGUAIA',
            'CACHOEIRO DE ITAPEMIRIM',
            'CAICÓ',
            'AGROPECUARIA UMUARAMA ',
            'MONTE ALEGRE',
            'MUNDICO COELHO',
            'AEROPORTO DE PIRENÓPOLIS',
            'MARACÁS',
            'MOCAMBINHO',
            'MANDUCA LEAO',
            'MUCURI',
            'SÃO MATEUS',
            'PORTO DE MOZ',
            'RIO CAPIM',
            'PROGRESSO',
            'VIRGÍLIO TÁVORA',
            'ORIXIMINÁ',
            'PICOS',
            'PATOS DE MINAS',
            'PORTO GRANDE',
            'PATROCÍNIO',
            'MORRO DE SÃO PAULO',
            'PORTO DE VILA DO CONDE',
            'SÃO SEBASTIÃO DO PARAÍSO',
            'SOUSA',
            'CANGAPARA',
            'CURURU',
            'CARIRI',
            'ROSA BRANCA',
            'OSCAR LARANJEIRAS',
            'SAO JOSE  ',
            'SALINÓPOLIS',
            'SOURE',
            'TEIXEIRA DE FREITAS',
            'ÓBIDOS',
            'JUSCELINO KUBITSCHECK',
            'AGROPALMA ',
            'PEREGRINO FILHO',
            'UBÁ',
            'AÇU',
            'ARAÇUAÍ',
            'ULIANÓPOLIS  ',
            'VALENÇA',
            'AEROCLUBE DA BAHIA',
            'BREVES',
            'VALENTE',
            'WILMA REBELO',
            'PRIMAVERA',
            'CHAVES',
            'ALMEIRIM',
            'TITO TEIXEIRA',
            'FAZENDA SOCOCO  ',
            'POUSO ALEGRE',
            'CAYENNE-ROCHAMBEAU AIRPORT',
            'CAPITÃN ROLDEN AIRPORT (OR CAPITÃN FAP DAVID ABENZUR RENGIFO AIRPORT)',
            'JORGE CHÃVEZ INTERNATIONAL AIRPORT',
            'JORGE CHÃVEZ INTERNATIONAL AIRPORT',
            'LAS PALMAS AIR BASE (MILITARY)',
            'CORONEL FAP FRANCISCO SECADA VIGNETTA AIRPORT',
            'RODRÃGUEZ BALLÃ“N INTERNATIONAL AIRPORT',
            'CAPITÃN FAP CARLOS MARTÃNEZ DE PINILLOS AIRPORT',
            'CAPITÃN FAP RENÃN ELÃAS OLIVERA AIRPORT',
            'SAN PABLO AIRPORT',
            'CORONEL FAP CARLOS CIRIANI SANTA ROSA AIRPORT',
            'PADRE JOSE DE ALDAMIZ INTERNATIONAL AIRPORT',
            'SUBTENIENTE FAP ALEJANDRO VELASCO ASTETE INTERNATIONAL AIRPORT',
            'FAZENDA NOVA JERUSALÉM',
            'ESTRELA DALVA',
            'AEROCLUBE ',
            'BELÉM NOVO',
            'CACADOR',
            'OLAVO CECCO RIGON',
            'CANELA',
            'MUNICIPAL FRANCISCO DE MATOS PEREIRA',
            'ERECHIM',
            'AEROPORTO PAULO ABDALA',
            'WALTER BÜNDCHEN',
            'IJUÍ',
            'SANTA TEREZINHA',
            'GERALDO GUIAS DE AQUINO',
            'CACOAL',
            'SALTO SANTIAGO',
            'GAUDÊNCIO MACHADO RAMOS',
            'FAZENDA CORRENTÃO',
            'SANTA MARIA',
            'NOVO HAMBURGO',
            'GUARANTÃ',
            'HÉLIO WASUM',
            'JUVENAL LOUREIRO CARDOSO',
            'SANTOS DUMONT',
            'PORECATU',
            'SANTA CRUZ DO SUL',
            'TOLEDO',
            'AEROPORTO REGIONAL PLÍNIO ALARCON',
            'ORLANDO DE CARVALHO',
            'GUARAPUAVA',
            'ÂNGELO PONZONI',
            'SANTA ROSA',
            'C/C CARLOS A. CURBELO DE LAGUNA DEL SAUCE INTERNATIONAL AIRPORT',
            'RICARDO DETOMASI AIRPORT',
            'CARRASCO GRAL. CESÃREO L. BERISSO INTERNATIONAL AIRPORT',
            'EL JAGÃœEL AIRPORT',
            'PTE. GRAL. Ã“SCAR D. GESTIDO INTERNATIONAL AIRPORT',
            'NUEVA HESPÃ‰RIDES INTERNATIONAL AIRPORT',
            'GENERAL JOSE ANTONIO ANZOÃTEGUI INTERNATIONAL AIRPORT',
            'BARINAS AIRPORT',
            'GENERAL JOSÃ‰ FRANCISCO BERMÃšDEZ AIRPORT',
            'JOSEFA CAMEJO INTERNATIONAL AIRPORT',
            'LA CHINITA INTERNATIONAL AIRPORT',
            'DEL CARIBE INTERNATIONAL AIRPORT (GEN. SANTIAGO MARINO AIRPORT)',
            'SIMON BOLIVAR INTERNATIONAL AIRPORT (MAIQUETIA INTERNATIONAL AIRPORT)',
            'MATURÃN AIRPORT',
            'MANUEL CARLOS PIAR GUAYANA AIRPORT',
            'ARTURO MICHELENA INTERNATIONAL AIRPORT',
            'JUAN PABLO PEREZ ALFONSO AIRPORT',
            'UAICAS',
            'BARCELOS',
            'BARREIRINHA',
            'BORBA',
            'FAZENDA FARTURA BAIXAO NOVO',
            'AUARIS',
            'JPO SORRISO',
            'CARAUARI',
            'CAMPOS BELOS',
            'COLNIZA',
            'CAMPO NOVO DOS PARECIS',
            'COSTA MARQUES',
            'AERÓDROMO FAZENDA ELDORADO',
            'FAZENDA PIRATININGA',
            'DIAMANTINO',
            'ESTIRÃO DO EQUADOR',
            'EIRUNEPÉ',
            'CANARANA',
            'CARACARAI ',
            'FEIJÓ',
            'FLORES',
            'SÃO FÉLIX DO ARAGUAIA',
            'GURUPI',
            'ARAGUAÍNA',
            'PALMEIRAS DE GOIÁS',
            'AEROPORTO DE SANTA HELENA DO GOIÁS',
            'FAZENDA OLHO DAGUA',
            'FRANCISCO CORREA DA CRUZ',
            'IPIRANGA',
            'MINAÇU',
            'JUARA',
            'JI-PARANÁ',
            'JUÍNA',
            'BITTENCOURT',
            'FAZENDA COLIBRI',
            'JURUENA',
            'JATAÍ',
            'CÁCERES',
            'CACOAL',
            'CALDAS NOVAS',
            'COARI',
            'LÁBREA',
            'GENERAL LEITE DE CASTRO',
            'ESTANCIA SANTO ANTONIO',
            'MATUPA',
            'MAUÉS',
            'NOVO ARIPUANÃ',
            'ARUANÃ',
            'NOVO CAMPO',
            'NOVA OLINDA DO NORTE',
            'NIQUELÂNDIA',
            'ANÁPOLIS',
            'FONTE BOA',
            'MOURA',
            'PARI-CACHOEIRA',
            'POUSO DAAGUIA  ',
            'PITINGA',
            'JÚLIO BÉLEM',
            'PALMAS',
            'PIRAGUASSU',
            'ESTÂNCIA MONTENEGRO',
            'RONDONÓPOLIS',
            'ARIPUANA  ',
            'PRESIDENTE JOÃO BATISTA FIGUEIREDO',
            'SÃO JOAQUIM',
            'TAPURUQUARA',
            'TANGARÁ DA SERRA',
            'FAZENDA TUCUNARE',
            'SÃO MIGUEL DO ARAGUAIA',
            'SURUCUCU OU SURUCURU',
            'URUCU',
            'VILA RICA',
            'ESTANCIA ROSALIA',
            'PORANGATU',
            'BARCELOS  ',
            'URUAÇU',
            'REGIONAL ORLANDO VILLAS BOAS',
            'XAVANTINA',
            'FAZENDA ILHA CAMARGO',
            'PRAINHA',
            'AEROPORTO FAZENDA NOVA VIENA',
            'USINA SÃO SIMÃO',
            'CHEDDI JAGAN INTERNATIONAL AIRPORT',
            'VC BIRD INTERNATIONAL AIRPORT',
            'GRANTLEY ADAMS INTERNATIONAL AIRPORT',
            'FORT-DE-FRANCE - LE LAMENTIN AIRPORT',
            'POINTE-Ã€-PITRE - LE RAIZET AIRPORT',
            'RAFAEL HERNÃNDEZ AIRPORT',
            'LUIS MUÃ‘OZ MARÃN INTERNATIONAL AIRPORT',
            'QUEEN BEATRIX INTERNATIONAL AIRPORT',
            'HATO INTERNATIONAL AIRPORT',
            'PRINCESS JULIANA INTERNATIONAL AIRPORT',
            'ARTHUR NAPOLEON RAYMOND ROBINSON INTERNATIONAL AIRPORT',
            'PIARCO INTERNATIONAL AIRPORT',
            'BORYSPIL INTERNATIONAL AIRPORT',
            'SHEREMETYEVO INTERNATIONAL AIRPORT',
            'VNUKOVO AIRPORT',
            'ANGKOR INTERNATIONAL AIRPORT',
            'HONG KONG INTERNATIONAL AIRPORT',
            'AGRA AIRPORT/AGRA AIR FORCE STATION',
            'CHENNAI INTERNATIONAL AIRPORT',
            'MALE INTERNATIONAL AIRPORT',
            'DON MUANG INTERNATIONAL AIRPORT (OLD BANGKOK INTERNATIONAL AIRPORT)',
            'SOEKARNO HATTA INTERNATIONAL AIRPORT',
            'SELETAR AIRPORT',
            'SINGAPORE CHANGI AIRPORT/CHANGI AIR BASE (JOINT CIVILIAN-MILITARY USAGE)',
            'CAIRNS INTERNATIONAL AIRPORT',
            'BEIJING CAPITAL INTERNATIONAL AIRPORT'
        ];

        return view('site.index', compact('title', 'aeroports', 'numberAdults', 'numberChildres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        echo "teste aqui tamem";
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function show(Home $home)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function edit(Home $home)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Home $home)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Home  $home
     * @return \Illuminate\Http\Response
     */
    public function destroy(Home $home)
    {
        //
    }

    public function getEdu()
    {
        return view('welcome');
    }
}
